# Generated by Django 5.2.1 on 2025-06-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0200_merge_20250527_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
